-- 创建时间:2021-01-12

return {
	{
		path = "sys_act_base_001_normal",
		key = "normal",
		style_type = "normal",
		beginTime = -1,
		endTime = -1,
		prefab_list={"ActivityYearLeftPrefab_normal", "ActivityYearPanel_normal"},
	},
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly",
	-- 	beginTime = 1611619200,
	-- 	endTime = 1612195199,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly", "ActivityYearLeftPrefab_weekly", "SYSACTBASEEnterPrefab_weekly"},
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly2",
	-- 	beginTime = 1612224000,
	-- 	endTime = 1612799999,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly2", "ActivityYearLeftPrefab_weekly2", "SYSACTBASEEnterPrefab_weekly2"},
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly3",
	-- 	beginTime = 1612828800,
	-- 	endTime = 1613404799,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly3", "ActivityYearLeftPrefab_weekly3", "SYSACTBASEEnterPrefab_weekly3"},
	-- 	desc = "过大年",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly4",
	-- 	beginTime = 1613433600,
	-- 	endTime = 1614009599,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly4", "ActivityYearLeftPrefab_weekly4", "SYSACTBASEEnterPrefab_weekly4"},
	-- 	desc = "迎财神",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly5",
	-- 	beginTime = 1614038400,
	-- 	endTime = 1614614399,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly5", "ActivityYearLeftPrefab_weekly5", "SYSACTBASEEnterPrefab_weekly5"},
	-- 	desc = "闹元宵",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly6",
	-- 	beginTime = 1614643200,
	-- 	endTime = 1615219199,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly6", "ActivityYearLeftPrefab_weekly6", "SYSACTBASEEnterPrefab_weekly6"},
	-- 	desc = "女神节",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly7",
	-- 	beginTime = 1615248000,
	-- 	endTime = 1615823999,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly7", "ActivityYearLeftPrefab_weekly7", "SYSACTBASEEnterPrefab_weekly7"},
	-- 	desc = "315狂欢",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly8",
	-- 	beginTime = 1615852800,
	-- 	endTime = 1616428799,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly8", "ActivityYearLeftPrefab_weekly8", "SYSACTBASEEnterPrefab_weekly8"},
	-- 	desc = "春暖花开",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly9",
	-- 	beginTime = 1616457600,
	-- 	endTime = 1617033599,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly9", "ActivityYearLeftPrefab_weekly9", "SYSACTBASEEnterPrefab_weekly9"},
	-- 	desc = "月末狂欢",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly10",
	-- 	beginTime = 1617062400,
	-- 	endTime = 1617638399,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly10", "ActivityYearLeftPrefab_weekly10", "SYSACTBASEEnterPrefab_weekly10"},
	-- 	desc = "清明有礼",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly11",
	-- 	beginTime = 1617667200,
	-- 	endTime = 1618243199,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly11", "ActivityYearLeftPrefab_weekly11", "SYSACTBASEEnterPrefab_weekly11"},
	-- 	desc = "龙腾祈福",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly12",
	-- 	beginTime = 1618272000,
	-- 	endTime = 1618847999,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly12", "ActivityYearLeftPrefab_weekly12", "SYSACTBASEEnterPrefab_weekly12"},
	-- 	desc = "欢乐四月天",
	-- },
	-- ---为了与文件夹名字统一，直接跳过13
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly14",
	-- 	beginTime = 1619481600,
	-- 	endTime = 1620662399,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly14", "ActivityYearLeftPrefab_weekly14", "SYSACTBASEEnterPrefab_weekly14"},
	-- 	desc = "五一乐翻天",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly15",
	-- 	beginTime = 1620662400,
	-- 	endTime = 1621267199,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly15", "ActivityYearLeftPrefab_weekly15", "SYSACTBASEEnterPrefab_weekly15"},
	-- 	desc = "欢乐嘉年华",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly16",
	-- 	beginTime = 1621296000,
	-- 	endTime = 1621871999,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly16", "ActivityYearLeftPrefab_weekly16", "SYSACTBASEEnterPrefab_weekly16"},
	-- 	desc = "欢乐五月天",
	-- },
	{
		key = "weekly",
		style_type = "weekly17",
		beginTime = 1627344000,
		endTime = 1627919999,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly17", "ActivityYearLeftPrefab_weekly17", "SYSACTBASEEnterPrefab_weekly17"},
		desc = "送话费",
	},
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly18",
	-- 	beginTime = 1622505600,
	-- 	endTime = 1623081599,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly18", "ActivityYearLeftPrefab_weekly18", "SYSACTBASEEnterPrefab_weekly18"},
	-- 	desc = "欢乐六一",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly19",
	-- 	beginTime = 1623110400,
	-- 	endTime = 1623686399,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly19", "ActivityYearLeftPrefab_weekly19", "SYSACTBASEEnterPrefab_weekly19"},
	-- 	desc = "粽情端午",
	-- },
	-- {
	-- 	key = "weekly",
	-- 	style_type = "weekly20",
	-- 	beginTime = 1623715200,
	-- 	endTime = 1624291199,
	-- 	condi_key = nil,
	-- 	prefab_list={"ActivityYearPanel_weekly20", "ActivityYearLeftPrefab_weekly20", "SYSACTBASEEnterPrefab_weekly20"},
	-- 	desc = "父亲节狂欢",
	-- },
	{
		key = "weekly",
		style_type = "weekly23",
		beginTime = 1625529600,
		endTime = 1626105599,
		condi_key = "cpl_notcjj",
		prefab_list={"ActivityYearPanel_weekly23", "ActivityYearLeftPrefab_weekly23", "SYSACTBASEEnterPrefab_weekly23"},
		desc = "一起嗨啤",
	},
	{
		key = "weekly",
		style_type = "weekly22",
		beginTime = 1624924800,
		endTime = 1627315199,
		condi_key = "cpl_cjj",
		prefab_list={"ActivityYearPanel_weekly22", "ActivityYearLeftPrefab_weekly22", "SYSACTBASEEnterPrefab_weekly22"},
		desc = "消暑盛宴",
	},
		{
		key = "weekly",
		style_type = "weekly24",
		beginTime = 1626134400,
		endTime = 1626710399,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly24", "ActivityYearLeftPrefab_weekly24", "SYSACTBASEEnterPrefab_weekly24"},
		desc = "夏日狂欢",
	},
	{
		key = "weekly",
		style_type = "weekly25",
		beginTime = 1626739200,
		endTime = 1627315199,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly25", "ActivityYearLeftPrefab_weekly25", "SYSACTBASEEnterPrefab_weekly25"},
		desc = "夏日狂欢",
	},
	{
		key = "weekly",
		style_type = "weekly26",
		beginTime = 1627948800,
		endTime = 1628524799,
		condi_key = "cpl_notcjj",
		prefab_list={"ActivityYearPanel_weekly26", "ActivityYearLeftPrefab_weekly26", "SYSACTBASEEnterPrefab_weekly26"},
		desc = "初秋礼遇",
	},
	{
		key = "weekly",
		style_type = "weekly27",
		beginTime = 1627948800,
		endTime = 1630339199,
		condi_key = "cpl_cjj",
		prefab_list={"ActivityYearPanel_weekly27", "ActivityYearLeftPrefab_weekly27", "SYSACTBASEEnterPrefab_weekly27"},
		desc = "七夕祈福",
	},
	{
		key = "weekly",
		style_type = "weekly28",
		beginTime = 1628553600,
		endTime = 1629129599,
		condi_key = "cpl_notcjj",
		prefab_list={"ActivityYearPanel_weekly28", "ActivityYearLeftPrefab_weekly28", "SYSACTBASEEnterPrefab_weekly28"},
		desc = "七夕祈福",
	},
	{
		key = "weekly",
		style_type = "weekly29",
		beginTime = 1629158400,
		endTime = 1629734399,
		condi_key = "actp_own_task_p_drop_act_nor",
		prefab_list={"ActivityYearPanel_weekly29", "ActivityYearLeftPrefab_weekly29", "SYSACTBASEEnterPrefab_weekly29"},
		desc = "8月清凉节",
	},
	{
		key = "weekly",
		style_type = "weekly30",
		beginTime = 1629763200,
		endTime = 1630339199,
		condi_key = "actp_own_task_p_drop_act_nor",
		prefab_list={"ActivityYearPanel_weekly30", "ActivityYearLeftPrefab_weekly30", "SYSACTBASEEnterPrefab_weekly30"},
		desc = "送话费",
	},
	{
		key = "weekly",
		style_type = "weekly31",
		beginTime = 1630368000,
		endTime = 1630943999,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly31", "ActivityYearLeftPrefab_weekly31", "SYSACTBASEEnterPrefab_weekly31"},
		desc = "欢乐九月",
	},
	{
		key = "weekly",
		style_type = "weekly32",
		beginTime = 1630972800,
		endTime = 1631548799,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly32", "ActivityYearLeftPrefab_weekly32", "SYSACTBASEEnterPrefab_weekly32"},
		desc = "欢乐庆典",
	},
	{
		key = "weekly",
		style_type = "weekly33",
		beginTime = 1631577600,
		endTime = 1632153599,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly33", "ActivityYearLeftPrefab_weekly33", "SYSACTBASEEnterPrefab_weekly33"},
		desc = "欢乐嘉年华",
	},
	{
		key = "weekly",
		style_type = "weekly34",
		beginTime = 1632182400,
		endTime = 1632758399,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly34", "ActivityYearLeftPrefab_weekly34", "SYSACTBASEEnterPrefab_weekly34"},
		desc = "情满中秋",
	},
	{
		key = "weekly",
		style_type = "weekly35",
		beginTime = 1632787200,
		endTime = 1633967999,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly35", "ActivityYearLeftPrefab_weekly35", "SYSACTBASEEnterPrefab_weekly35"},
		desc = "国庆快乐",
	},
	{
		key = "weekly",
		style_type = "weekly36",
		beginTime = 1633996800,
		endTime = 1634572799,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly36", "ActivityYearLeftPrefab_weekly36", "SYSACTBASEEnterPrefab_weekly36"},
		desc = "重阳祈福",
	},
	{
		key = "fkfl",
		style_type = "fkfl1",
		beginTime = -1,
		endTime = -1,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_fkfl1", "ActivityYearLeftPrefab_fkfl1", "SYSACTBASEEnterPrefab_fkfl1"},
		desc = "疯狂返利",
	},
	{
		key = "weekly",
		style_type = "weekly37",
		beginTime = 1634601600,
		endTime = 1635177599,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly37", "ActivityYearLeftPrefab_weekly37", "SYSACTBASEEnterPrefab_weekly37"},
		desc = "十月送话费",
	},
	{
		key = "weekly",
		style_type = "weekly38",
		beginTime = 1635206400,
		endTime = 1635782399,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly38", "ActivityYearLeftPrefab_weekly38", "SYSACTBASEEnterPrefab_weekly38"},
		desc = "万圣节狂欢",
	},
	{
		key = "hghd",
		style_type = "hghd1",
		beginTime = -1,
		endTime = -1,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_hghd1", "ActivityYearLeftPrefab_hghd1", "SYSACTBASEEnterPrefab_hghd1"},
		desc = "老玩家回归活动",
	},
	{
		key = "weekly",
		style_type = "weekly39",
		beginTime = 1635811200,
		endTime = 1636387199,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly39", "ActivityYearLeftPrefab_weekly39", "SYSACTBASEEnterPrefab_weekly39"},
		desc = "欢乐十一月",
	},
	{
		key = "weekly",
		style_type = "weekly40",
		beginTime = 1636416000,
		endTime = 1637596799,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly40", "ActivityYearLeftPrefab_weekly40", "SYSACTBASEEnterPrefab_weekly40"},
		desc = "狂欢双十一",
	},
	{
		key = "weekly",
		style_type = "weekly41",
		beginTime = 1637625600,
		endTime = 1638201599,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly41", "ActivityYearLeftPrefab_weekly41", "SYSACTBASEEnterPrefab_weekly41"},
		desc = "感恩节",
	},
	{
		key = "weekly",
		style_type = "weekly42",
		beginTime = 1638230400,
		endTime = 1638806399,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly42", "ActivityYearLeftPrefab_weekly42", "SYSACTBASEEnterPrefab_weekly42"},
		desc = "欢乐十二月",
	},
	{
		key = "weekly",
		style_type = "weekly43",
		beginTime = 1638835200,
		endTime = 1639411199,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly43", "ActivityYearLeftPrefab_weekly43", "SYSACTBASEEnterPrefab_weekly43"},
		desc = "雪球大作战",
	},
	{
		key = "weekly",
		style_type = "weekly44",
		beginTime = 1639440000,
		endTime = 1640015999,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly44", "ActivityYearLeftPrefab_weekly44", "SYSACTBASEEnterPrefab_weekly44"},
		desc = "年末狂欢",
	},
	{
		key = "weekly",
		style_type = "weekly45",
		beginTime = 1640044800,
		endTime = 1640620799,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly45", "ActivityYearLeftPrefab_weekly45", "SYSACTBASEEnterPrefab_weekly45"},
		desc = "圣诞狂欢",
	},
	{
		key = "weekly",
		style_type = "weekly46",
		beginTime = 1640649600,
		endTime = 1641225599,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly46", "ActivityYearLeftPrefab_weekly46", "SYSACTBASEEnterPrefab_weekly46"},
		desc = "元旦快乐",
	},
	{
		key = "weekly",
		style_type = "weekly47",
		beginTime = 1641254400,
		endTime = 1641830399,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly47", "ActivityYearLeftPrefab_weekly47", "SYSACTBASEEnterPrefab_weekly47"},
		desc = "狂欢庆典",
	},
	{
		key = "weekly",
		style_type = "weekly48",
		beginTime = 1641859200,
		endTime = 1643039999,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly48", "ActivityYearLeftPrefab_weekly48", "SYSACTBASEEnterPrefab_weekly48"},
		desc = "欢乐嘉年华",
	},
	{
		key = "weekly",
		style_type = "weekly49",
		beginTime = 1643068800,
		endTime = 1645459199,
		condi_key = nil,
		prefab_list={"ActivityYearPanel_weekly49", "ActivityYearLeftPrefab_weekly49", "SYSACTBASEEnterPrefab_weekly49"},
		desc = "辞旧岁贺新年",
	},
}


